### ISSUE TITLE
関数名

### ISSUE THREAD

**Issue by Ichii0924** [c0b21057/ProjExD#1]
https://github.com/c0b21057/ProjExD/blob/9c81b816e6d2942dd20bdcb075fb0f56ade2a84b/ex01/alphabet.py#L26

関数名がローマ字だと読みにくいから簡単な英単語の方がいいかも
ex)def ans:
     def alpha_anser

**Comment by c0b21057** [comment]
ありがとうございます。修正しました。

**Comment by c0b21057** [comment]
ありがとうございます。へんこうしました。
